apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-03-18T19:58:02Z
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Heapster
    task: monitoring
  name: heapster
  namespace: kube-system
  resourceVersion: "33070"
  selfLink: /api/v1/namespaces/kube-system/services/heapster
  uid: 31cde0d1-0c15-11e7-9bd9-00e07041ea76
spec:
  clusterIP: 192.168.69.171
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    k8s-app: heapster
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

