kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-storage-pvc
  annotations:
    "volume.beta.kubernetes.io/storage-class": ceph
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
