apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: 2017-03-18T19:57:59Z
  generation: 4
  labels:
    k8s-app: grafana
    task: monitoring
  name: monitoring-grafana
  namespace: kube-system
  resourceVersion: "11167704"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/monitoring-grafana
  uid: 2fd8a783-0c15-11e7-9bd9-00e07041ea76
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: grafana
      task: monitoring
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: grafana
        task: monitoring
    spec:
      containers:
      - env:
        - name: INFLUXDB_HOST
          value: monitoring-influxdb
        - name: GRAFANA_PORT
          value: "3000"
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          value: /
        image: gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-storage-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-03-18T19:57:59Z
    lastUpdateTime: 2017-03-18T19:57:59Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  replicas: 1
  updatedReplicas: 1

